# Generated by Django 4.2.13 on 2024-10-26 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_detected', models.BooleanField()),
                ('species', models.CharField(max_length=255)),
                ('habitat', models.CharField(blank=True, max_length=255, null=True)),
                ('diet', models.CharField(blank=True, max_length=255, null=True)),
                ('average_size', models.CharField(blank=True, max_length=50, null=True)),
                ('behavior', models.TextField(blank=True, null=True)),
                ('lifespan', models.CharField(blank=True, max_length=50, null=True)),
                ('visual_characteristics', models.TextField(blank=True, null=True)),
                ('prompt_tokens', models.IntegerField()),
                ('completion_tokens', models.IntegerField()),
                ('total_tokens', models.IntegerField()),
                ('model_used', models.CharField(max_length=255)),
                ('time_taken', models.FloatField()),
                ('image_size', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
