name: aquaware
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 2.0.0+1

flutter_launcher_icons: # dart run flutter_launcher_icons:generate
  android: "launcher_icon"
  image_path: "assets/aquaware.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  android_12:
    color: "#031726"
    image: assets/aquaware.png
    android: true
  color: "#031726"
  image: assets/aquaware.png
  android: true

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  confetti: ^0.8.0
  connectivity_plus: ^6.1.3
  fl_chart: ^0.68.0
  fl_heatmap: ^0.4.5
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.35.3
  flutter_expandable_fab: ^2.3.0
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_secure_storage: ^9.2.2
  flutter_signin_button: ^2.0.0
  flutter_svg: ^2.0.10+1
  flutter_web_auth: ^0.6.0
  font_awesome_flutter: ^9.0.0
  get: ^4.6.6
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  intl: any
  network_info_plus: ^6.1.3
  package_info: ^2.0.2
  package_info_plus: ^8.0.2
  permission_handler: ^11.4.0
  rive: ^0.13.5
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.2.0+3
  syncfusion_flutter_charts: ^26.1.42
  uni_links: ^0.5.1
  url_launcher: ^6.3.1
  wifi_info_flutter: ^2.0.2
  wifi_scan: ^0.4.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/
    - assets/fonts/
    - assets/flags/
    - assets/images/
    - assets/icons/
    - assets/RiveAssets/

  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Thin.ttf
          weight: 100
        - asset: assets/fonts/Sora-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Sora-Light.ttf
          weight: 300
        - asset: assets/fonts/Sora-Regular.ttf
          weight: 400
        - asset: assets/fonts/Sora-Medium.ttf
          weight: 500
        - asset: assets/fonts/Sora-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Sora-Bold.ttf
          weight: 700
        - asset: assets/fonts/Sora-ExtraBold.ttf
          weight: 800