name: aquaware
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.2.0+1

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/Aquaware_logo_filled_cropped.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  android_12:
    color: "#ffffff"
    image: assets/Aquaware_logo_filled_wtext_bigger_margin.png
    android: true
  color: "#ffffff"
  image: assets/Aquaware_logo_filled_wtext_bigger_margin.png
  android: true

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  fl_chart: ^0.68.0
  fl_heatmap: ^0.4.5
  flutter:
    sdk: flutter
  flutter_expandable_fab: ^2.3.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  flutter_secure_storage: ^9.2.2
  flutter_signin_button: ^2.0.0
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^9.0.0
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  package_info: ^2.0.2
  package_info_plus: ^8.0.2
  rive: ^0.13.5
  shared_preferences: ^2.2.3
  syncfusion_flutter_charts: ^26.1.42

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/
    - assets/icons/
    - assets/Backgrounds/Spline.png
    - assets/RiveAssets/
