# Generated by Django 4.2.13 on 2024-08-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('DEBUG', 'DEBUG'), ('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR'), ('CRITICAL', 'CRITICAL')], max_length=10)),
                ('message', models.TextField()),
                ('logger_name', models.CharField(max_length=255)),
                ('pathname', models.CharField(blank=True, max_length=255, null=True)),
                ('func_name', models.CharField(blank=True, max_length=255, null=True)),
                ('line_no', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
