# Generated by Django 4.2.13 on 2024-08-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APILogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=255)),
                ('status_code', models.IntegerField()),
                ('remote_addr', models.GenericIPAddressField()),
                ('user_agent', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='LogEntry',
        ),
    ]
