# Generated by Django 4.2.13 on 2024-08-22 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logs', '0003_apilogentry_post_data_apilogentry_query_params_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apilogentry',
            name='response_time',
        ),
        migrations.AlterField(
            model_name='apilogentry',
            name='method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='apilogentry',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='apilogentry',
            name='remote_addr',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='apilogentry',
            name='status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apilogentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='apilogentry',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
