# Generated by Django 4.2.13 on 2024-08-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_remove_apilogentry_response_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apilogentry',
            name='post_data',
        ),
        migrations.RemoveField(
            model_name='apilogentry',
            name='query_params',
        ),
        migrations.RemoveField(
            model_name='apilogentry',
            name='request_body',
        ),
        migrations.RemoveField(
            model_name='apilogentry',
            name='user',
        ),
        migrations.AlterField(
            model_name='apilogentry',
            name='method',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='apilogentry',
            name='path',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='apilogentry',
            name='remote_addr',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='apilogentry',
            name='status_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='apilogentry',
            name='user_agent',
            field=models.CharField(max_length=255),
        ),
    ]
