# Generated by Django 4.2.13 on 2024-08-22 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logs', '0005_remove_apilogentry_post_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apilogentry',
            name='post_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apilogentry',
            name='query_params',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apilogentry',
            name='request_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apilogentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='apilogentry',
            name='method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='apilogentry',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='apilogentry',
            name='remote_addr',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='apilogentry',
            name='status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apilogentry',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
