# Generated by Django 4.2.13 on 2024-08-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_apilogentry_post_data_apilogentry_query_params_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apilogentry',
            options={'verbose_name': 'API Log Entry', 'verbose_name_plural': 'API Log Entries'},
        ),
        migrations.RemoveField(
            model_name='apilogentry',
            name='post_data',
        ),
        migrations.AddField(
            model_name='apilogentry',
            name='execution_time',
            field=models.FloatField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apilogentry',
            name='headers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apilogentry',
            name='response_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apilogentry',
            name='method',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apilogentry',
            name='path',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apilogentry',
            name='remote_addr',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apilogentry',
            name='status_code',
            field=models.IntegerField(),
        ),
    ]
