# Generated by Django 4.2.13 on 2024-10-13 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseasedetection',
            old_name='image_size',
            new_name='base64_image_size',
        ),
    ]
