# Generated by Django 4.2.13 on 2024-10-26 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0002_rename_image_size_diseasedetection_base64_image_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseasedetection',
            name='certainty',
        ),
    ]
