# Generated by Django 4.2.13 on 2024-10-26 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0003_remove_diseasedetection_certainty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseasedetection',
            old_name='fish_detected',
            new_name='animal_detected',
        ),
    ]
