POST http://aquaware-production.up.railway.app/entries/add_entry
Content-Type: application/json
Authorization: Token fce755bf14f24067f225746935edbe7f0507c5ae

{
  "temperature": "{{$random.float(10, 30)}}",
  "ph": "{{$random.float(3, 10)}}",
  "co2" : "{{$random.float(0, 100)}}"
}

###

GET http://127.0.0.1:8000/entries/get_all_entries
Content-Type: application/json
Authorization: Token fce755bf14f24067f225746935edbe7f0507c5ae

{}
