# Generated by Django 4.2.13 on 2024-09-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
