# Generated by Django 4.2.13 on 2024-10-03 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('environments', '0003_userenvironmentsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userenvironmentsubscription',
            name='environment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribed_users', to='environments.environment'),
        ),
        migrations.AlterField(
            model_name='userenvironmentsubscription',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
