# Generated by Django 4.2.13 on 2025-03-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0005_alter_environment_environment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='is_setup',
            field=models.BooleanField(default=False),
        ),
    ]
