# Generated by Django 4.2.13 on 2024-07-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watervalue',
            name='generated',
            field=models.BooleanField(default=False),
        ),
    ]
