# Generated by Django 4.2.13 on 2024-10-03 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0003_userenvironmentsubscription'),
        ('water', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watervalue',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='water_values', to='environments.environment'),
        ),
    ]
