# Generated by Django 4.2.13 on 2024-07-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0002_watervalue_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watervalue',
            name='value',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
