# Generated by Django 4.2.13 on 2024-08-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0003_alter_watervalue_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watervalue',
            name='measured_at',
            field=models.DateTimeField(),
        ),
    ]
