# Generated by Django 4.2.13 on 2024-08-13 18:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0004_alter_watervalue_measured_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='watervalue',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
