# Generated by Django 4.2.13 on 2024-08-15 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aquariums', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('water', '0005_watervalue_added_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAlertSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=255)),
                ('under_value', models.FloatField(blank=True, null=True)),
                ('above_value', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aquariums.aquarium')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
