# Generated by Django 4.2.13 on 2024-08-15 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aquariums', '0001_initial'),
        ('water', '0006_useralertsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useralertsetting',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water.waterparameter'),
        ),
        migrations.AlterUniqueTogether(
            name='useralertsetting',
            unique_together={('user', 'aquarium', 'parameter')},
        ),
    ]
