# Generated by Django 4.2.13 on 2025-01-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.CharField(default='6524cb218d8a8866259d94f56bf27d9715f2bb6e', max_length=40, unique=True),
        ),
    ]
