# Generated by Django 4.2.13 on 2025-01-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_code_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.CharField(default='d499e19c6b167c5ec4cb16ee5252d6800f4ad77d', max_length=40, unique=True),
        ),
    ]
