# Generated by Django 4.2.13 on 2025-01-14 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_reset_code_user_reset_code_expiration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.CharField(default='b4d99c189b6f81f19d8d00c23ebf601bf33fe791', max_length=40, unique=True),
        ),
        migrations.CreateModel(
            name='DeveloperAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='7e685e592b8f88cc71a5a2ad0cc9e76ccc4c494b', max_length=40, unique=True)),
                ('name', models.CharField(help_text="Name of the API key, e.g., 'My App'", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Purpose or additional information about this API key', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developer_api_keys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
