# Generated by Django 4.2.13 on 2025-01-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_api_key_developerapikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.CharField(default='34d201c01cb5362d254a25fb2b941a43dbae910e', max_length=40, unique=True),
        ),
        migrations.DeleteModel(
            name='DeveloperAPIKey',
        ),
    ]
