# Generated by Django 4.2.13 on 2025-03-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_api_key_delete_developerapikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.CharField(default='735191', max_length=40, unique=True),
        ),
    ]
